# Utilizing pandas / python, I dig into the details of a local red light camera system grouping by days of week and summarizing data into incidents per year and running descriptive statistics overall

Tools used:
- Python / pandas

In [15]:
import pandas as pd
speed = pd.read_csv("Speed_Camera_Violations.csv")
speed.head()

,ADDRESS,CAMERA ID,VIOLATION DATE,VIOLATIONS,X COORDINATE,Y COORDINATE,LATITUDE,LONGITUDE,LOCATION
0,7738 S WESTERN,CHI065,07/08/2014,65,NaN,NaN,NaN,NaN,NaN
1,1111 N HUMBOLDT,CHI010,07/16/2014,56,NaN,NaN,NaN,NaN,NaN
2,5520 S WESTERN,CHI069,07/08/2014,10,NaN,NaN,NaN,NaN,NaN
3,1111 N HUMBOLDT,CHI010,07/26/2014,101,NaN,NaN,NaN,NaN,NaN
4,1111 N HUMBOLDT,CHI010,07/27/2014,92,NaN,NaN,NaN,NaN,NaN

In [118]:
# Mean Violations per Camera - 28.9
speed['VIOLATIONS'].mean()

28.880448742383635

In [18]:
speed['VIOLATION DATE'] = pd.to_datetime(speed['VIOLATION DATE'])
speed['day_of_week'] = speed['VIOLATION DATE'].dt.weekday_name
speed.head()

,ADDRESS,CAMERA ID,VIOLATION DATE,VIOLATIONS,X COORDINATE,Y COORDINATE,LATITUDE,LONGITUDE,LOCATION,day_of_week
0,7738 S WESTERN,CHI065,2014-07-08,65,NaN,NaN,NaN,NaN,NaN,Tuesday
1,1111 N HUMBOLDT,CHI010,2014-07-16,56,NaN,NaN,NaN,NaN,NaN,Wednesday
2,5520 S WESTERN,CHI069,2014-07-08,10,NaN,NaN,NaN,NaN,NaN,Tuesday
3,1111 N HUMBOLDT,CHI010,2014-07-26,101,NaN,NaN,NaN,NaN,NaN,Saturday
4,1111 N HUMBOLDT,CHI010,2014-07-27,92,NaN,NaN,NaN,NaN,NaN,Sunday

In [29]:
speed.groupby(['day_of_week']).sum().sort_values(by=('VIOLATIONS'), ascending = False)
# most violations issued on Friday at 753,468

,VIOLATIONS,X COORDINATE,Y COORDINATE,LATITUDE,LONGITUDE
day_of_week,,,,,
Friday,753468,2.969780e+10,4.849572e+10,1.072352e+06,-2.246282e+06
Thursday,730603,3.063207e+10,5.002385e+10,1.106136e+06,-2.317053e+06
Tuesday,708276,3.147777e+10,5.140274e+10,1.136724e+06,-2.381161e+06
Wednesday,705136,3.070936e+10,5.014615e+10,1.108929e+06,-2.322930e+06
Monday,686724,2.976620e+10,4.860353e+10,1.074738e+06,-2.251272e+06
Saturday,676715,1.893861e+10,3.090150e+10,6.827700e+05,-1.429940e+06
Sunday,663801,1.892335e+10,3.087836e+10,6.822298e+05,-1.428801e+06

In [49]:
# Create Year column
speed['YEAR'] = speed['VIOLATION DATE'].dt.year
speed.head()

,ADDRESS,CAMERA ID,VIOLATION DATE,VIOLATIONS,X COORDINATE,Y COORDINATE,LATITUDE,LONGITUDE,LOCATION,day_of_week,YEAR
0,7738 S WESTERN,CHI065,2014-07-08,65,NaN,NaN,NaN,NaN,NaN,Tuesday,2014
1,1111 N HUMBOLDT,CHI010,2014-07-16,56,NaN,NaN,NaN,NaN,NaN,Wednesday,2014
2,5520 S WESTERN,CHI069,2014-07-08,10,NaN,NaN,NaN,NaN,NaN,Tuesday,2014
3,1111 N HUMBOLDT,CHI010,2014-07-26,101,NaN,NaN,NaN,NaN,NaN,Saturday,2014
4,1111 N HUMBOLDT,CHI010,2014-07-27,92,NaN,NaN,NaN,NaN,NaN,Sunday,2014

In [72]:
speed_cams = speed.groupby(['YEAR', 'CAMERA ID']).sum()

In [64]:
speed["YEAR"].value_counts()
# The number of total violations hovering around 38,0000.

2016    38998
2017    38346
2018    38251
2015    37872
2014    17054
Name: YEAR, dtype: int64

In [132]:
speed[speed.YEAR == 2014].groupby('CAMERA ID').sum() #143 cameras
speed[speed.YEAR == 2015].groupby('CAMERA ID').sum() #150 cameras
speed[speed.YEAR == 2016].groupby('CAMERA ID').sum() #150 cameras
speed[speed.YEAR == 2017].groupby('CAMERA ID').sum() #150 cameras
speed[speed.YEAR == 2018].groupby('CAMERA ID').sum() #162 cameras

# Unique Cameras per year. Upshifted from 143 to 150 to 162 in 2018.

,VIOLATIONS,X COORDINATE,Y COORDINATE,LATITUDE,LONGITUDE,YEAR
CAMERA ID,,,,,,
CHI003,43831,4.120791e+08,6.944047e+08,15069.242303,-31495.669456,724103
CHI004,11794,4.158509e+08,7.000420e+08,15194.708421,-31757.661622,730154
CHI005,3933,4.221865e+08,6.820200e+08,15181.817543,-31826.877613,732171
CHI007,19286,4.121684e+08,6.670323e+08,14847.365205,-31128.076000,716035
CHI008,7749,4.169449e+08,6.872190e+08,15159.499640,-31753.976930,730154
CHI009,12539,4.192715e+08,6.915289e+08,15244.661500,-31929.315035,734188
CHI010,21539,NaN,NaN,NaN,NaN,734188
CHI011,4949,3.997817e+08,6.596598e+08,14497.166499,-30345.764732,697882
CHI013,17292,4.292303e+08,6.787054e+08,15172.566511,-31801.139455,732171
CHI014,19809,4.220408e+08,6.783828e+08,15245.222132,-32011.499336,736205
CHI015,3907,4.074954e+08,6.556451e+08,14742.830008,-30961.534132,712001
CHI018,13171,4.127575e+08,6.637148e+08,14911.631611,-31309.993346,720069
CHI019,13064,4.153600e+08,6.801367e+08,15030.024685,-31483.992325,724103
CHI020,12185,4.153774e+08,6.801658e+08,15030.104117,-31483.927493,724103
CHI021,39204,4.223546e+08,6.907120e+08,15279.048870,-32010.015316,736205
CHI022,1685,2.275706e+08,3.569658e+08,8129.686880,-17094.503865,393315
CHI023,3707,2.333987e+08,3.661422e+08,8338.205091,-17532.849538,403400
CHI024,14928,3.820347e+08,6.420304e+08,13898.783314,-29031.428971,667627
CHI025,5013,3.915985e+08,6.557714e+08,14229.824690,-29731.927581,683763
CHI026,2790,8.234498e+07,1.365627e+08,2978.135760,-6225.853528,143207
CHI027,2993,8.233899e+07,1.365727e+08,2978.163344,-6225.875261,143207
CHI028,10767,2.004276e+08,3.328148e+08,7256.763153,-15170.828872,348941
CHI029,17740,4.310594e+08,6.818801e+08,15254.624816,-31978.334729,736205
CHI030,2765,2.025010e+08,3.293823e+08,7357.374622,-15439.301418,354992
CHI031,8181,2.059418e+08,3.348752e+08,7482.450942,-15702.514483,361043
CHI032,2778,2.060076e+08,3.349759e+08,7482.726043,-15702.270541,361043
CHI033,3343,2.258876e+08,3.643030e+08,8039.779123,-16824.469992,387264
CHI034,2226,2.129317e+08,3.434297e+08,7579.162181,-15860.621077,365077
CHI035,1770,3.853979e+08,6.023231e+08,13642.981882,-28652.218368,659559
CHI036,3553,4.007294e+08,6.262962e+08,14185.438689,-29791.260472,685780
...,...,...,...,...,...,...
CHI138,11632,4.344201e+08,6.772865e+08,15241.940381,-31966.159285,736205
CHI139,223,1.246630e+08,2.020110e+08,4441.058587,-9288.650812,213802
CHI140,1190,3.628488e+08,5.564623e+08,12600.291133,-26436.345374,609134
CHI141,3267,3.953360e+08,6.062398e+08,13726.881680,-28799.686409,663593
CHI142,10680,4.363532e+08,6.685896e+08,15144.634721,-31775.363554,732171
CHI143,3861,1.948769e+08,3.155557e+08,6989.367802,-14639.689323,336839
CHI144,23383,4.241855e+08,6.855990e+08,15228.288719,-31911.439657,734188
CHI145,5057,2.383590e+08,3.695332e+08,8347.397418,-17514.580236,403400
CHI146,13785,1.709371e+08,2.701714e+08,6058.108263,-12704.864434,292465
CHI147,21205,4.138159e+08,6.991796e+08,15192.380643,-31765.166590,730154
CHI148,4029,2.088549e+08,3.297481e+08,7394.935677,-15507.987728,357009
CHI149,68587,4.128038e+08,6.975427e+08,15151.218640,-31676.928291,728137
CHI154,980,3.427887e+08,5.417107e+08,12303.413724,-25866.305362,595015
CHI156,2504,2.027321e+08,3.469028e+08,7515.515371,-15714.005608,361043
CHI157,3096,4.137821e+08,6.881788e+08,15088.814939,-31581.571896,726120
CHI158,3928,1.991877e+08,3.408874e+08,7389.007037,-15451.186447,354992
CHI159,4693,4.147409e+08,6.896116e+08,15129.418188,-31670.011349,728137
CHI160,5794,2.057492e+08,3.391043e+08,7494.060071,-15703.111309,361043
CHI161,4030,4.182381e+08,6.953729e+08,15255.229963,-31933.010349,734188
CHI162,2209,2.023865e+08,3.334950e+08,7368.662723,-15439.614729,354992
CHI163,2649,2.058216e+08,3.391926e+08,7494.300887,-15702.843511,361043
CHI164,572,1.676133e+08,2.708040e+08,6059.915400,-12717.033078,292465
CHI165,622,3.172249e+08,5.012901e+08,11385.811071,-23937.292872,550641
CHI166,123,9.361724e+07,1.513023e+08,3385.264782,-7104.052222,163377
CHI167,157,1.098026e+08,1.774611e+08,3970.393391,-8331.896184,191615
CHI168,8236,4.248501e+08,6.731067e+08,15193.993961,-31909.358692,734188
CHI169,12667,4.096462e+08,6.491606e+08,14651.608323,-30769.848303,707967
CHI170,2045,4.145318e+08,6.566273e+08,14818.762527,-31119.703905,716035
CHI171,399,1.526340e+08,2.516236e+08,5493.911183,-11484.568679,264227
CHI172,1534,2.062152e+08,3.400155e+08,7423.168568,-15517.373844,357009

In [135]:
speed.describe()
# Standard deviation of violations is 36.6 as compared to mean violation of 28.9. Huge variability between violations per camera per date.
# Median violation at 16, significantly lower than the mean. 
# There are cameras that recorded as little as 1 violation per day. Are these still necessary?
# In 2018, unique camera amount increased by 12, but total violations decreased. Why is this?

,VIOLATIONS,X COORDINATE,Y COORDINATE,LATITUDE,LONGITUDE,YEAR
count,170521.000000,1.639590e+05,1.639590e+05,163959.000000,163959.000000,170521.000000
mean,28.880449,1.159712e+06,1.893473e+06,41.863389,-87.689229,2016.251394
std,36.636151,1.570560e+04,3.212393e+04,0.088338,0.057135,1.296573
min,1.000000,1.121638e+06,1.820629e+06,41.663174,-87.828317,2014.000000
25%,7.000000,1.149783e+06,1.868078e+06,41.793493,-87.725084,2015.000000
50%,16.000000,1.159169e+06,1.898488e+06,41.877243,-87.689803,2016.000000
75%,37.000000,1.167170e+06,1.920991e+06,41.939040,-87.662810,2017.000000
max,479.000000,1.203645e+06,1.943342e+06,42.000260,-87.529848,2018.000000